#
#   py/lscode/Makefile -- Neurofit: Least-squares code and interface module
#

all:
	C:\Python22\python Setup.py build
	COPY build\lib.win32-2.2\LSInter.pyd ..

clean:
	RMDIR /S/Q build


	